package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.AbstractBorder;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/** @file GameBrief.java
 @brief Clase  <em>GameBrief</em>.
 @class GameBrief
 */

/**
 * @brief Clase GameBrief que carga la partida guardada con todos sus atributos.
 * @author Judith Almoño Gómez
 */

public class GameBrief extends JPanel {

    /**
     * idLabel es "Partida: " + el id de la partida
     */
    private JLabel idLabel;
    /**
     * sizeLabel es "Tamaño: " + el tamaño del kakuro de la partida
     */
    private JLabel sizeLabel;
    /**
     * diffLabel es "Dificultad: " + la dificultad del kakuro de la partida
     */
    private JLabel diffLabel;
    /**
     * timeLable es el tiempo de la partida
     */
    private JLabel timeLabel;

    public JPanel panel1;
    public JPanel panel2;

    /**
     * pathImage es el fondo del panel de la partida a escoger
     */
    public String pathImage = "fondo-game-brief.png";

    /**
     * difficulty es la dificultad del kakuro de la partida
     */
    private int difficulty;

    /**
     * @param id         representa el id de la partida
     * @param rowSize    representa el numero de filas del kakuro de la partida
     * @param columnSize representa el numero de columnas del kakuro de la partida
     * @param diff       representa la dificultad del kakuro de la partida
     * @param time       representa el tiempo de la partida
     * @brief Constructora
     */
    public GameBrief(int id, int rowSize, int columnSize, int diff, String time) {
        super();

        difficulty = diff;

        $$$setupUI$$$();
        idLabel.setFont(Utils.roboto.deriveFont(16f));
        idLabel.setForeground(Color.decode(Utils.colorDarkBlue));

        sizeLabel.setFont(Utils.roboto.deriveFont(16f));
        sizeLabel.setForeground(Color.BLACK);

        diffLabel.setFont(Utils.roboto.deriveFont(16f));
        if (diff == 1) diffLabel.setForeground(Color.GREEN);
        else if (diff == 2) diffLabel.setForeground(Color.ORANGE);
        else if (diff == 3) diffLabel.setForeground(Color.red);

        timeLabel.setFont(Utils.digital.deriveFont(35f));
        timeLabel.setForeground(Color.decode("#1b5e20"));

        this.idLabel.setText("Partida " + id);
        this.sizeLabel.setText("Tamaño: " + rowSize + "x" + columnSize);
        this.diffLabel.setText("Dificultad: " + diff);
        this.timeLabel.setText(time);
    }

    private void createUIComponents() {
        panel2 = new ImageGame();
    }

    /**
     * @param option representa si la partida está seleccionada o no
     * @brief Función que cambia las propiedades al seleccionar o deseleccionar la partida
     */
    public void changeImage(int option) {
        if (option == 0) {
            pathImage = "fondo-game-brief.png";
            panel2.repaint();
            idLabel.setForeground(Color.decode(Utils.colorDarkBlue));
            sizeLabel.setForeground(Color.BLACK);
            if (difficulty == 1) diffLabel.setForeground(Color.GREEN);
            else if (difficulty == 2) diffLabel.setForeground(Color.ORANGE);
            else if (difficulty == 3) diffLabel.setForeground(Color.red);
            timeLabel.setForeground(Color.decode("#1b5e20"));
        } else {
            pathImage = "Partida_1.png";
            panel2.repaint();
            idLabel.setForeground(Color.WHITE);
            sizeLabel.setForeground(Color.WHITE);
            diffLabel.setForeground(Color.WHITE);
            timeLabel.setForeground(Color.WHITE);
        }

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-1973022));
        panel1.setMaximumSize(new Dimension(262, 110));
        panel1.setMinimumSize(new Dimension(262, 110));
        panel1.setPreferredSize(new Dimension(262, 110));
        panel2.setLayout(new GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-1973022));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(252, 100), new Dimension(252, 100), new Dimension(252, 100), 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 3, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(30, -1), new Dimension(30, -1), new Dimension(30, -1), 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(10, -1), new Dimension(10, -1), new Dimension(10, -1), 0, false));
        idLabel = new JLabel();
        idLabel.setText("Partida");
        panel2.add(idLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sizeLabel = new JLabel();
        sizeLabel.setText("Tamaño: ");
        panel2.add(sizeLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        diffLabel = new JLabel();
        diffLabel.setText("Dificultad: ");
        panel2.add(diffLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        timeLabel = new JLabel();
        timeLabel.setText("time");
        panel2.add(timeLabel, new GridConstraints(0, 2, 3, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(100, -1), new Dimension(100, -1), new Dimension(100, -1), 0, false));
        final Spacer spacer4 = new Spacer();
        panel1.add(spacer4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    /**
     * @brief Función para cargar el fondo del panel de la partida
     */
    class ImageGame extends JPanel {
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(new ImageIcon(getClass().getClassLoader().getResource("images/" + pathImage)).getImage(), 0, 0, null);
        }
    }
}
